#!/usr/bin/env bash
# stack-detect.sh — Detect technologies from package.json and config files
# Outputs JSON suitable for generating stack-lock.json
# Usage: stack-detect.sh [project-dir]
#   project-dir: path to project root (default: current directory)

set -euo pipefail

PROJECT_DIR="${1:-.}"

if [[ ! -d "$PROJECT_DIR" ]]; then
  echo "Error: $PROJECT_DIR is not a directory" >&2
  exit 1
fi

cd "$PROJECT_DIR"

# --- Detection functions ---

detect_surrealdb() {
  local version="unknown"
  local sdk=""

  # Check package.json for SDK
  if [[ -f package.json ]]; then
    sdk=$(grep -o '"surrealdb":\s*"[^"]*"' package.json 2>/dev/null | head -1 | sed 's/.*"\([^"]*\)"$/\1/' || true)
  fi

  # Check node_modules for installed version
  if [[ -f node_modules/surrealdb/package.json ]]; then
    local installed
    installed=$(grep -o '"version":\s*"[^"]*"' node_modules/surrealdb/package.json | head -1 | sed 's/.*"\([^"]*\)"$/\1/' || true)
    if [[ "$installed" == 2.* ]]; then
      version="v3"
      sdk="surrealdb@${installed}"
    elif [[ "$installed" == 1.* ]]; then
      version="v2"
      sdk="surrealdb@${installed}"
    fi
  elif [[ -n "$sdk" ]]; then
    # Infer from package.json spec
    if [[ "$sdk" == ^2.* || "$sdk" == 2.* || "$sdk" == "latest" ]]; then
      version="v3"
    else
      version="v2"
    fi
    sdk="surrealdb@${sdk}"
  fi

  if [[ -n "$sdk" ]] || grep -rql "surrealdb\|surql\|SurrealDB" --include="*.ts" --include="*.js" --include="*.surql" . 2>/dev/null; then
    echo "\"surrealdb\": { \"version\": \"${version}\", \"sdk\": \"${sdk}\", \"audit\": true }"
    return 0
  fi
  return 1
}

detect_nuxt() {
  if [[ -f nuxt.config.ts || -f nuxt.config.js ]]; then
    local version="4"
    local sdk=""

    if [[ -f package.json ]]; then
      # Check for Nuxt UI
      if grep -q '"@nuxt/ui"' package.json 2>/dev/null; then
        local ui_ver
        ui_ver=$(grep -o '"@nuxt/ui":\s*"[^"]*"' package.json | head -1 | sed 's/.*"\([^"]*\)"$/\1/' || true)
        sdk="@nuxt/ui@${ui_ver}"
      fi

      # Check for Nuxt UI Pro (shouldn't exist in v4)
      if grep -q '"@nuxt/ui-pro"' package.json 2>/dev/null; then
        echo "  // WARNING: @nuxt/ui-pro detected. Nuxt UI v4 merged Pro into @nuxt/ui." >&2
      fi
    fi

    echo "\"nuxt\": { \"version\": \"${version}\", \"sdk\": \"${sdk}\", \"audit\": true }"
    return 0
  fi
  return 1
}

detect_tailwind() {
  if [[ -f package.json ]] && grep -q '"tailwindcss"' package.json 2>/dev/null; then
    local version="4"

    # v4 uses CSS imports, v3 uses config files
    if [[ -f tailwind.config.js || -f tailwind.config.ts || -f tailwind.config.cjs ]]; then
      version="3"
      echo "  // WARNING: tailwind config file detected. Tailwind v4 uses CSS-first config." >&2
    fi

    echo "\"tailwind\": { \"version\": \"${version}\", \"audit\": true }"
    return 0
  fi
  return 1
}

detect_bun() {
  if [[ -f bunfig.toml || -f bun.lockb || -f bun.lock ]]; then
    local version="latest"
    if command -v bun &>/dev/null; then
      version=$(bun --version 2>/dev/null || echo "latest")
    fi
    echo "\"bun\": { \"version\": \"${version}\", \"audit\": true }"
    return 0
  fi
  return 1
}

detect_hono() {
  if [[ -f package.json ]] && grep -q '"hono"' package.json 2>/dev/null; then
    local version="latest"
    if [[ -f node_modules/hono/package.json ]]; then
      version=$(grep -o '"version":\s*"[^"]*"' node_modules/hono/package.json | head -1 | sed 's/.*"\([^"]*\)"$/\1/' || true)
    fi
    echo "\"hono\": { \"version\": \"${version}\", \"audit\": true }"
    return 0
  fi
  return 1
}

# --- Main output ---

echo "{"
echo "  \"_readme\": \"Auto-generated by stack-detect.sh. Review and approve before committing.\","
echo "  \"schema_version\": \"1.0\","
echo "  \"locked\": \"$(date +%Y-%m-%d)\","
echo "  \"approved_by\": \"pending\","
echo "  \"tier\": \"experiment\","
echo "  \"technologies\": {"

techs=()

# Run each detector, collect results
for detector in detect_surrealdb detect_nuxt detect_tailwind detect_bun detect_hono; do
  result=$($detector 2>/dev/null) && techs+=("    $result") || true
done

# Output with proper comma separation
for i in "${!techs[@]}"; do
  if [[ $i -lt $((${#techs[@]} - 1)) ]]; then
    echo "${techs[$i]},"
  else
    echo "${techs[$i]}"
  fi
done

echo "  },"
echo "  \"services\": {},"
echo "  \"paths\": {},"
echo "  \"exceptions\": []"
echo "}"
